apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-devop-ifriuac
  labels:
    app: tp-devop-ifriuac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-devop-ifriuac
  template:
    metadata:
      labels:
        app: tp-devop-ifriuac
    spec:
      containers:
      - name: tp-devop-ifriuac
        image: lcherubin/tp-devop-ifriuac:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: tp-devop-ifriuac
spec:
  type: NodePort
  selector:
    app: tp-devop-ifriuac
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000